# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- powershell: |
    # does not work as documented here https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch

    # Using the env var directly:
    Write-Host "This does not work: $env:apiLogin"

    # Using the mapped env var:
    Write-Host "This works: $env:BITLY_API_LOGIN"    # Recommended
  env:
    BITLY_API_KEY: $(apiKey)
    BITLY_API_LOGIN: $(apiLogin)
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build $(buildConfiguration)'
- script: dotnet test --configuration $(buildConfiguration)
  displayName: 'Run tests ($(buildConfiguration))'
