# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  BITLY_KEY_LOGIN1: $(apiLogin)
  BITLY_KEY_LOGIN2: $env:apiLogin
  BITLY_KEY_LOGIN3: '%apiLogin%'
  BITLY_KEY_LOGIN4: '$apiLogin'
  BITLY_KEY_LOGIN5: $apiLogin


steps:
- task: PowerShell@2
  inputs:
    filePath: './setEnvironmentVariables.ps1'
    arguments: '$env:apiLogin $env:apiKey'
  displayName: 'PowerShell Script'
- powershell: |
    # Using an input-macro:
    Write-Host "This works: $(apiLogin)"

    # Using the env var directly:
    Write-Host "This does not work: $env:apiLogin"

    # Using the mapped env var:
    Write-Host "This works: $env:MY_MAPPED_ENV_VAR"    # Recommended
  env:
    MY_MAPPED_ENV_VAR: $(apiLogin)
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build $(buildConfiguration)'
- script: dotnet test --configuration $(buildConfiguration)
  displayName: 'Run tests ($(buildConfiguration))'
