# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'


steps:
- script: dotnet build --configuration $(buildConfiguration) ./src/BitlyHelper.csproj
  displayName: 'Build $(buildConfiguration)'
- script: dotnet test --configuration $(buildConfiguration) ./tests/BitLyTests.csproj
  displayName: 'Run tests ($(buildConfiguration))'
  env:
    VAULT_URL: $(vaultUrl)
    APPLICATION_ID: $(appId)
    APPLICATION_SECRET: $(appSecret)
- script: dotnet pack --no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) ./src/BitlyHelper.csproj
  displayName: 'NuGet pack'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'nuget'