# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  BITLY_API_LOGIN: $(apiLogin)
  BITLY_API_KEY: $(apiKey)

steps:
- script: dotnet build --configuration $(buildConfiguration) $(Build.Repository.LocalPath)/src/BitLyHelper.csproj
  displayName: 'Build $(buildConfiguration)'
- script: dotnet test --configuration $(buildConfiguration) $(Build.Repository.LocalPath)/tests/BitLyTests.csproj
  displayName: 'Run tests ($(buildConfiguration))'
- script: dotnet pack --no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) $(Build.Repository.LocalPath)/src/BitLyHelper.csproj
  displayName: 'NuGet pack'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'nuget'